"""Tests for omniscan.update.download (card U6)."""

from __future__ import annotations

import hashlib
import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

import httpx
import pytest

from omniscan.update.download import (
    StagedUpdate,
    check_for_update,
    download_update,
    parse_checksums,
)
from omniscan.update.github import Asset, ReleaseInfo, UpdateError
from omniscan.update.version import parse_version

ASSET_NAME = "omniscan-windows-x64.zip"
ASSET_PARTS = tuple(bytes([65 + i]) * 100 for i in range(10))  # ten 100-byte chunks
ASSET_BYTES = b"".join(ASSET_PARTS)
ASSET_SHA256 = hashlib.sha256(ASSET_BYTES).hexdigest()
BASE = "https://github.com/owner/repo/releases/download/v1.0.0"


def mock_client(handler: Callable[[httpx.Request], httpx.Response]) -> httpx.Client:
    return httpx.Client(transport=httpx.MockTransport(handler), timeout=5.0)


def sums_text(name: str = ASSET_NAME, sha256: str = ASSET_SHA256) -> str:
    return f"{sha256}  {name}\n"


def make_release(asset_name: str = ASSET_NAME) -> ReleaseInfo:
    return ReleaseInfo(
        tag="v1.0.0",
        version=parse_version("v1.0.0"),
        prerelease=False,
        notes="",
        published_at=None,
        assets=(
            Asset(asset_name, f"{BASE}/{asset_name}", len(ASSET_BYTES)),
            Asset("SHA256SUMS", f"{BASE}/SHA256SUMS", len(sums_text())),
        ),
    )


class FakeServer:
    """MockTransport handler serving SHA256SUMS (behind a redirect) and one build asset."""

    def __init__(
        self,
        *,
        asset_name: str = ASSET_NAME,
        sums: str | None = None,
        asset_parts: tuple[bytes, ...] = ASSET_PARTS,
        asset_status: int = 200,
    ) -> None:
        self.asset_name = asset_name
        self.sums = sums if sums is not None else sums_text(asset_name)
        self.asset_parts = asset_parts
        self.asset_status = asset_status
        self.sums_requests = 0
        self.asset_requests = 0

    def handler(self, request: httpx.Request) -> httpx.Response:
        name = request.url.path.rsplit("/", 1)[-1]
        if name == "SHA256SUMS":
            self.sums_requests += 1
            if "direct" not in request.url.params:
                return httpx.Response(302, headers={"Location": f"{request.url}?direct=1"})
            return httpx.Response(200, text=self.sums)
        if name == self.asset_name:
            self.asset_requests += 1
            if self.asset_status != 200:
                return httpx.Response(self.asset_status)
            return httpx.Response(
                200,
                content=iter(self.asset_parts),
                headers={"Content-Length": str(sum(len(part) for part in self.asset_parts))},
            )
        raise AssertionError(f"unexpected URL {request.url}")

    def client(self) -> httpx.Client:
        return mock_client(self.handler)


# ---------------------------------------------------------------- parse_checksums


def test_parse_checksums_accepts_both_forms_comments_and_case() -> None:
    text = "\n".join(
        [
            "# generated by sha256sum",
            "",
            f"{'A' * 64}  {ASSET_NAME}",
            f"{'b' * 64} *other.zip",
        ]
    )
    assert parse_checksums(text) == {ASSET_NAME: "a" * 64, "other.zip": "b" * 64}


@pytest.mark.parametrize(
    "line",
    [
        "zz  name.zip",
        f"{'a' * 63}  name.zip",
        "no digest at all",
        f"{'a' * 64}",  # digest without a name
    ],
)
def test_parse_checksums_rejects_bad_lines(line: str) -> None:
    with pytest.raises(UpdateError, match="bad line in SHA256SUMS"):
        parse_checksums(line)


def test_parse_checksums_reports_the_offending_line() -> None:
    with pytest.raises(UpdateError, match=r"'zz  name\.zip'"):
        parse_checksums("zz  name.zip\n")


# ---------------------------------------------------------------- download_update


def test_download_update_happy_path(tmp_path: Path) -> None:
    server = FakeServer()
    progress: list[tuple[int, int | None]] = []
    staged = download_update(
        server.client(),
        make_release(),
        tmp_path,
        key="windows-x64",
        on_progress=lambda done, total: progress.append((done, total)),
    )

    assert staged == StagedUpdate(
        version=parse_version("v1.0.0"),
        tag="v1.0.0",
        path=tmp_path / "v1.0.0" / ASSET_NAME,
        sha256=ASSET_SHA256,
        asset=ASSET_NAME,
    )
    assert (tmp_path / "v1.0.0" / ASSET_NAME).read_bytes() == ASSET_BYTES
    meta = json.loads((tmp_path / "v1.0.0" / "staged.json").read_text(encoding="utf-8"))
    assert meta["tag"] == "v1.0.0"
    assert meta["version"] == "1.0.0"
    assert meta["asset"] == ASSET_NAME
    assert meta["sha256"] == ASSET_SHA256
    assert "T" in meta["downloaded_at"]  # a timestamp

    dones = [done for done, _ in progress]
    assert dones == sorted(dones)  # monotonic
    assert dones[0] > 0
    assert progress[-1] == (len(ASSET_BYTES), len(ASSET_BYTES))


def test_download_update_checksum_mismatch(tmp_path: Path) -> None:
    server = FakeServer(sums=f"{'0' * 64}  {ASSET_NAME}\n")
    with pytest.raises(UpdateError, match=r"checksum mismatch for omniscan-windows-x64\.zip"):
        download_update(server.client(), make_release(), tmp_path, key="windows-x64")
    assert not list(tmp_path.rglob("*.part"))
    assert not (tmp_path / "v1.0.0" / ASSET_NAME).exists()


def test_download_update_missing_sums_entry(tmp_path: Path) -> None:
    server = FakeServer(sums=f"{ASSET_SHA256}  some-other-asset.zip\n")
    with pytest.raises(UpdateError, match=r"SHA256SUMS has no entry for omniscan-windows-x64\.zip"):
        download_update(server.client(), make_release(), tmp_path, key="windows-x64")
    assert server.asset_requests == 0  # the build is never requested


def test_download_update_reuses_a_matching_file(tmp_path: Path) -> None:
    server = FakeServer()
    download_update(server.client(), make_release(), tmp_path, key="windows-x64")
    assert server.asset_requests == 1
    download_update(server.client(), make_release(), tmp_path, key="windows-x64")
    assert server.asset_requests == 1  # the second call did not touch the asset URL
    assert server.sums_requests >= 2  # but checksums are still fetched
    assert (tmp_path / "v1.0.0" / ASSET_NAME).read_bytes() == ASSET_BYTES


def test_download_update_redownloads_a_wrong_file(tmp_path: Path) -> None:
    server = FakeServer()
    target = tmp_path / "v1.0.0" / ASSET_NAME
    target.parent.mkdir(parents=True)
    target.write_bytes(b"stale content")
    download_update(server.client(), make_release(), tmp_path, key="windows-x64")
    assert target.read_bytes() == ASSET_BYTES
    assert server.asset_requests == 1


def test_download_update_http_500(tmp_path: Path) -> None:
    server = FakeServer(asset_status=500)
    with pytest.raises(UpdateError, match=r"HTTP 500 while downloading omniscan-windows-x64\.zip"):
        download_update(server.client(), make_release(), tmp_path, key="windows-x64")
    assert not list(tmp_path.rglob("*.part"))
    assert not (tmp_path / "v1.0.0" / ASSET_NAME).exists()


def test_download_update_key_defaults_to_the_platform(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from omniscan.update import download as download_module

    monkeypatch.setattr(download_module, "platform_key", lambda: "linux-arm64")
    server = FakeServer(asset_name="omniscan-linux-arm64.zip")
    staged = download_update(server.client(), make_release("omniscan-linux-arm64.zip"), tmp_path)
    assert staged.asset == "omniscan-linux-arm64.zip"
    assert staged.path == tmp_path / "v1.0.0" / "omniscan-linux-arm64.zip"


# ---------------------------------------------------------------- check_for_update


def releases_payload(tags: tuple[str, ...]) -> list[dict[str, Any]]:
    return [
        {"tag_name": tag, "draft": False, "prerelease": "beta" in tag, "body": "", "assets": []}
        for tag in tags
    ]


def client_serving(tags: tuple[str, ...]) -> httpx.Client:
    return mock_client(lambda request: httpx.Response(200, json=releases_payload(tags)))


def test_check_for_update_finds_a_newer_release() -> None:
    release = check_for_update(
        client_serving(("v1.0.0", "v0.9.0")), repo="owner/repo", current=parse_version("v0.1.0")
    )
    assert release is not None
    assert release.tag == "v1.0.0"


def test_check_for_update_none_for_equal_or_older_current() -> None:
    client = client_serving(("v1.0.0",))
    assert check_for_update(client, repo="owner/repo", current=parse_version("v1.0.0")) is None
    assert check_for_update(client, repo="owner/repo", current=parse_version("v2.0.0")) is None


def test_check_for_update_ignores_prereleases_on_stable() -> None:
    client = client_serving(("v1.1.0-beta.1", "v1.0.0"))
    assert check_for_update(client, repo="owner/repo", current=parse_version("v1.0.0")) is None
    beta = check_for_update(client, repo="owner/repo", channel="beta", current=parse_version("v1.0.0"))
    assert beta is not None
    assert beta.tag == "v1.1.0-beta.1"


def test_check_for_update_uses_the_installed_version_by_default(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from omniscan.update import download as download_module
    from omniscan.update.version import Version

    monkeypatch.setattr(download_module, "current_version", lambda: Version(0, 1, 0, ()))
    release = check_for_update(client_serving(("v1.0.0",)), repo="owner/repo")
    assert release is not None
    assert release.tag == "v1.0.0"


def test_check_for_update_none_without_releases() -> None:
    assert check_for_update(client_serving(()), repo="owner/repo") is None
